# yaml-language-server: $schema=./quartz/plugins/quartz-plugins.schema.json
configuration:
  pageTitle: Notes on Statistics
  pageTitleSuffix: ""
  enableSPA: true
  enablePopovers: true
  locale: en-US
  baseUrl: whstats.github.io
  ignorePatterns:
    - private
    - templates
    - .obsidian
  theme:
    fontOrigin: googleFonts
    cdnCaching: true
    typography:
      header: '-apple-system-body, ui-sans-serif, -apple-system, "system-ui", "Segoe UI", Helvetica, "Apple Color Emoji", Arial, "sans-serif", "Segoe UI Emoji", "Segoe UI Symbol"'
      body: '-apple-system-body, ui-sans-serif, -apple-system, "system-ui", "Segoe UI", Helvetica, "Apple Color Emoji", Arial, "sans-serif", "Segoe UI Emoji", "Segoe UI Symbol"'
      code: Ubuntu Mono
    colors:
      lightMode:
        light: "#faf8f8"
        lightgray: "#e5e5e5"
        gray: "#b8b8b8"
        darkgray: "#464646"
        dark: "#272727"
        secondary: "#284b63"
        tertiary: "#84a59d"
        highlight: rgba(143, 159, 169, 0.15)
        textHighlight: "#d977062e"
      darkMode:
        light: "#161618"
        lightgray: "#393639"
        gray: "#646464"
        darkgray: "#d4d4d4"
        dark: "#ebebec"
        secondary: "#7b97aa"
        tertiary: "#84a59d"
        highlight: rgba(143, 159, 169, 0.15)
        textHighlight: "#d9770638"
plugins:
  - source: "@quartz-community/note-properties"
    enabled: true
    options:
      includeAll: false
      includedProperties:
        - description
        - tags
        - aliases
      excludedProperties: []
      hidePropertiesView: true
      delimiters: ---
      language: yaml
    order: 5
    layout:
      position: beforeBody
      priority: 15
      display: all
  - source: "@quartz-community/created-modified-date"
    enabled: true
    options:
      defaultDateType: modified
      priority:
        - frontmatter
        - git
        - filesystem
    order: 10
  - source: ./plugins/syntax-highlighting
    enabled: true
    options:
      theme:
        light: github-light
        dark: github-dark
      keepBackground: false
    order: 20
  - source: "@quartz-community/obsidian-flavored-markdown"
    enabled: true
    options:
      enableInHtmlEmbed: false
      enableCheckbox: true
    order: 30
  - source: "@quartz-community/github-flavored-markdown"
    enabled: true
    order: 40
  - source: ./plugins/lucide-content-icons
    enabled: true
    order: 42
  - source: ./plugins/table-of-contents
    enabled: true
    order: 50
    layout:
      position: right
      priority: 30
  - source: ./plugins/toc-active-heading
    enabled: true
    order: 55
  - source: ./plugins/keyboard-shortcuts
    enabled: true
    order: 56
  - source: "@quartz-community/crawl-links"
    enabled: true
    options:
      markdownLinkResolution: shortest
      externalLinkIcon: false
    order: 60
  - source: ./plugins/related-notes
    enabled: true
    order: 65
    layout:
      position: right
      priority: 40
      display: all
  - source: "@quartz-community/description"
    enabled: true
    order: 70
  - source: ./plugins/latex-delimiters
    enabled: true
    order: 75
  - source: ./plugins/markdown-actions
    enabled: true
    order: 90
    layout:
      position: beforeBody
      priority: 25
      display: all
  - source: "@quartz-community/latex"
    enabled: true
    options:
      renderEngine: katex
    order: 80
  - source: "@quartz-community/remove-draft"
    enabled: true
  - source: "@quartz-community/unlisted-pages"
    enabled: true
    options: {}
    order: 45
  - source: "@quartz-community/alias-redirects"
    enabled: true
  - source: "@quartz-community/content-index"
    enabled: true
    options:
      enableSiteMap: false
      enableRSS: false
  - source: "@quartz-community/favicon"
    enabled: true
  - source: "@quartz-community/content-page"
    enabled: true
  - source: ./plugins/folder-page
    enabled: true
  - source: "@quartz-community/tag-page"
    enabled: true
  - source: ./plugins/explorer
    enabled: true
    layout:
      position: left
      priority: 50
  - source: ./plugins/search
    enabled: true
    options:
      enablePreview: true
    layout:
      position: left
      priority: 20
      group: toolbar
      groupOptions:
        grow: true
  - source: "@quartz-community/article-title"
    enabled: true
    layout:
      position: beforeBody
      priority: 10
  - source: "@quartz-community/content-meta"
    enabled: false
    layout:
      position: beforeBody
      priority: 20
  - source: "@quartz-community/tag-list"
    enabled: false
    layout:
      position: beforeBody
      priority: 30
  - source: "@quartz-community/page-title"
    enabled: true
    layout:
      position: left
      priority: 10
  - source: ./plugins/darkmode
    enabled: true
    layout:
      position: left
      priority: 30
      group: toolbar
  - source: ./plugins/reader-mode
    enabled: true
    layout:
      position: left
      priority: 35
      group: toolbar
  - source: ./plugins/site-settings
    enabled: true
    layout:
      position: left
      priority: 40
      group: toolbar
  - source: ./plugins/breadcrumbs
    enabled: true
    layout:
      position: beforeBody
      priority: 5
      condition: not-index
  - source: "@quartz-community/spacer"
    enabled: true
    options: {}
    order: 25
    layout:
      position: left
      priority: 25
      display: mobile-only
layout:
  groups:
    toolbar:
      priority: 35
      direction: row
      gap: 0.5rem
  byPageType:
    "404":
      positions:
        beforeBody: []
        left: []
        right: []
    content: {}
    folder: {}
    tag: {}
